name: quad

default-extensions:
  - BlockArguments

dependencies:
  - aseon
  - async
  - base
  - butcher
  - hslogger
  - http-client
  - http-conduit
  - http-types
  - network
  - record-hasfield
  - record-hasfield
  - scotty
  - serialise
  - stm
  - time
  - typed-process
  - wai-cors
  - yaml

ghc-options:
  - -F -pgmF=record-dot-processor

library:
  source-dirs: src

executables:
  quad: 
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quad

tests:
  quad-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: 
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quad
      - hspec
